POSITIVE = 1
NEGATIVE = 0
DEFAULT_BRANCH = "Todas"
FLORIDA_BRANCH = "Universal Studios Florida"
JAPAN_BRANCH = "Universal Studios Japan"
SINGAPORE_BRANCH = "Universal Studios Singapore"
PANDEMIC_YEAR = 2019
DEFAULT_FILE = "default.jpeg"
DEFAULT_POS_FILE = "default_pos.jpeg"
DEFAULT_NEG_FILE = "default_neg.jpeg"
FLORIDA_FILE = "florida.jpeg"
FLORIDA_POS_FILE = "florida_pos.jpeg"
FLORIDA_NEG_FILE = "florida_neg.jpeg"
JAPAN_FILE = "japan.jpeg"
JAPAN_POS_FILE = "japan_pos.jpeg"
JAPAN_NEG_FILE = "japan_neg.jpeg"
SINGAPORE_FILE = "singapore.jpeg"
SINGAPORE_POS_FILE = "singapore_pos.jpeg"
SINGAPORE_NEG_FILE = "singapore_neg.jpeg"
RATING_FIVE = 5
RATING_FOUR = 4
RATING_THREE = 3
RATING_TWO = 2
RATING_ONE = 1