POSITIVE = 1
NEGATIVE = 0
FLORIDA_BRANCH = "Universal Studios Florida"
JAPAN_BRANCH = "Universal Studios Japan"
SINGAPORE_BRANCH = "Universal Studios Singapore"
PANDEMIC_YEAR = 2019
DEFAULT_FILE = "default.png"
DEFAULT_POS_FILE = "default_pos.png"
DEFAULT_NEG_FILE = "default_neg.png"
FLORIDA_FILE = "florida.png"
FLORIDA_POS_FILE = "florida_pos.png"
FLORIDA_NEG_FILE = "florida_neg.png"
JAPAN_FILE = "japan.png"
JAPAN_POS_FILE = "japan_pos.png"
JAPAN_NEG_FILE = "japan_neg.png"
SINGAPORE_FILE = "singapore.png"
SINGAPORE_POS_FILE = "singapore_pos.png"
SINGAPORE_NEG_FILE = "singapore_neg.png"
